// Mocks generated by Mockito 5.0.7 from annotations
// in garage_app/test/repository/vehicle_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:garage_app/data_provider/vehicle_state_data_provider.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [VehicleStateDataProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockVehicleStateDataProvider extends _i1.Mock
    implements _i2.VehicleStateDataProvider {
  MockVehicleStateDataProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<Map<String, String>> subscribeVehicleState(String? vin) =>
      (super.noSuchMethod(Invocation.method(#subscribeVehicleState, [vin]),
              returnValue: Stream<Map<String, String>>.empty())
          as _i3.Stream<Map<String, String>>);
  @override
  void updateVehicleState(String? vin, Map<String, String>? newState) => super
      .noSuchMethod(Invocation.method(#updateVehicleState, [vin, newState]),
          returnValueForMissingStub: null);
}
